services:
  node_app:
    image: pavelexpertov/project-arch-cw:sports_node_app
    ports:
      - "3000:3000"
    networks:
      - front-end
      - back-end
  mydb:
    image: pavelexpertov/project-arch-cw:tripdb
    networks:
      - back-end
  restore_db:
    image: pavelexpertov/project-arch-cw:tripdb
    command: "mongorestore -h mydb -d tripdb /mongo_backup/initial_backup/tripdb"
    restart: on-failure
    volumes:
      - ./mongo_backup:/mongo_backup
    networks:
      - back-end

networks:
  front-end: {}
  back-end: {}
